-- ============================================================================
-- Starter content. Generated by scripts/generate-seed.mjs - edit that file and
-- re-run it instead of editing this one by hand.
--
-- Safe to run once after the schema migration. Existing rows are left alone.
-- ============================================================================

update public.site_settings set
  site_name = 'Sujin Lee',
  hero_headline = 'Marketing, brand development,
product thinking
& visual storytelling.',
  hero_description = 'I develop ideas from concept to execution across branding, digital products, e-commerce, photography, and content.',
  hero_location = 'Based in Atlanta, Georgia.',
  hero_cta_label = 'Selected Work',
  selected_work_label = 'Selected Work',
  photography_label = 'Portrait',
  photography_subtitle = 'Photography · Retouching · Visual Direction',
  photography_description = 'Portrait photography and retouching focused on natural skin texture, composition, facial balance, and polished editorial presentation.',
  footer_location = 'Atlanta, GA',
  footer_copyright = '© 2026 Sujin Lee',
  footer_credit = 'Designed & developed by Sujin Lee.',
  contact_email = '',
  seo_title = 'Sujin Lee | Marketing, Brand Development & Creative Direction',
  seo_description = 'Portfolio of Sujin Lee: marketing, brand development, product thinking, e-commerce, visual content and creative direction. Based in Atlanta, Georgia.'
where id = 1 and hero_headline = '';

update public.profile set
  name = 'Sujin Lee',
  title = 'Marketing · Brand · Product',
  location = 'Atlanta, Georgia',
  about = 'I develop ideas from concept to execution across branding, digital products, e-commerce, photography, and content. My work moves from research and concept through visual identity, product development, and market execution, with a focus on refined, image-led storytelling.'
where id = 1 and name = '';

insert into public.education (school, college, degree, major, graduation, sort_order)
select * from (values
  ('Georgia State University', 'J. Mack Robinson College of Business', 'Bachelor of Business Administration', 'Marketing', 'Expected May 2027', 1)
) as v
where not exists (select 1 from public.education);

insert into public.social_links (label, kind, url, show_in_profile, show_in_footer, sort_order)
select * from (values
  ('LinkedIn', 'linkedin', '', true, true, 1),
  ('Instagram', 'instagram', '', true, true, 2),
  ('Email', 'email', '', true, true, 3),
  ('GitHub', 'github', '', true, false, 4)
) as v
where not exists (select 1 from public.social_links);

-- MAISON DE L’ÉTÉ
insert into public.projects (id, slug, status, is_featured, sort_order, content, published_at)
values ('11111111-1111-4111-8111-000000000001', 'maison-de-lete', 'published', true, 1, $json${
  "title": "MAISON DE L’ÉTÉ",
  "slug": "maison-de-lete",
  "subtitle": "Independent Fragrance Brand Development",
  "categories": [
    "Brand Development",
    "Creative Direction",
    "Product Development",
    "Visual Identity"
  ],
  "year": "2026",
  "dateRange": "2026–Present",
  "projectStatus": "In Development",
  "shortDescription": "An independently developed fragrance brand, taken from first concept through brand strategy, fragrance direction, visual identity, product prototyping, and supplier research.",
  "cover": null,
  "coverVideo": null,
  "tags": [
    "Fragrance",
    "Branding",
    "Packaging",
    "AI-Assisted Production"
  ],
  "projectUrl": "",
  "projectUrlLabel": "",
  "socialUrl": "",
  "socialLabel": "Instagram",
  "role": [
    "Founder",
    "Brand Strategy",
    "Creative Direction",
    "Product Development"
  ],
  "tools": [],
  "blocks": [
    {
      "id": "seed-001",
      "type": "paragraph",
      "text": "I independently developed MAISON DE L’ÉTÉ from its initial concept through brand strategy, fragrance direction, visual identity, product prototyping, supplier research, and digital content development.",
      "style": "lead",
      "columns": 1
    },
    {
      "id": "seed-002",
      "type": "caption",
      "text": "An active pre-launch project: the brand is in product development and has not been commercially released."
    },
    {
      "id": "seed-003",
      "type": "image_full",
      "media": null,
      "caption": "Campaign direction",
      "tag": ""
    },
    {
      "id": "seed-004",
      "type": "heading",
      "eyebrow": "01",
      "text": "Concept",
      "level": 2
    },
    {
      "id": "seed-005",
      "type": "paragraph",
      "text": "The concept phase defined the brand’s positioning, storytelling, naming, slogans, and copywriting, and shaped an emotional brand world around a clearly defined target customer and visual direction.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-006",
      "type": "image_large",
      "media": null,
      "caption": "Brand positioning and storytelling",
      "tag": ""
    },
    {
      "id": "seed-007",
      "type": "heading",
      "eyebrow": "02",
      "text": "Research & References",
      "level": 2
    },
    {
      "id": "seed-008",
      "type": "paragraph",
      "text": "Research informed every part of the brand: fragrance direction, packaging, photography, typography, product styling, and visual identity.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-009",
      "type": "moodboard",
      "images": [],
      "columns": 4,
      "caption": "Reference and moodboard imagery"
    },
    {
      "id": "seed-010",
      "type": "heading",
      "eyebrow": "03",
      "text": "Fragrance Development",
      "level": 2
    },
    {
      "id": "seed-011",
      "type": "paragraph",
      "text": "The project includes original fragrance concepts and custom physical prototypes. Custom fragrance prototypes were commissioned through independent perfumers.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-012",
      "type": "fragrance",
      "name": "When Summer Sleeps",
      "status": "Prototype",
      "story": "",
      "topNotes": "",
      "middleNotes": "",
      "baseNotes": "",
      "referenceImages": [],
      "prototypeImage": null,
      "prototypeCaption": "",
      "notes": ""
    },
    {
      "id": "seed-013",
      "type": "heading",
      "eyebrow": "04",
      "text": "Visual Identity",
      "level": 2
    },
    {
      "id": "seed-014",
      "type": "paragraph",
      "text": "Logo development, typography, label design, business card design, and the wider visual system, including the iterations behind each decision. Designs that were not physically manufactured are labelled as design concepts.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-015",
      "type": "image_grid",
      "images": [],
      "columns": 3,
      "aspect": "natural",
      "caption": "Logo development, typography, labels and business cards"
    },
    {
      "id": "seed-016",
      "type": "heading",
      "eyebrow": "05",
      "text": "Product & Packaging",
      "level": 2
    },
    {
      "id": "seed-017",
      "type": "paragraph",
      "text": "Perfume bottle design concepts, label applications, packaging concepts, mockups, iterations, and AI-assisted renderings. Conceptual renderings are presented as design concepts, not manufactured products.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-018",
      "type": "image_two_column",
      "images": [
        {
          "id": "seed-019",
          "media": null,
          "caption": "",
          "tag": "Design Concept"
        },
        {
          "id": "seed-020",
          "media": null,
          "caption": "",
          "tag": "Design Concept"
        }
      ]
    },
    {
      "id": "seed-021",
      "type": "image_grid",
      "images": [],
      "columns": 3,
      "aspect": "natural",
      "caption": "Packaging concepts and iterations"
    },
    {
      "id": "seed-022",
      "type": "heading",
      "eyebrow": "06",
      "text": "Production Research",
      "level": 2
    },
    {
      "id": "seed-023",
      "type": "paragraph",
      "text": "Research included contacting fragrance suppliers, perfume bottle manufacturers, packaging suppliers, printing suppliers, fragrance workshops, and workshops in Grasse, France. The purpose was to evaluate price, minimum order quantity, sourcing, production feasibility, and manufacturing options.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-024",
      "type": "image_grid",
      "images": [],
      "columns": 2,
      "aspect": "natural",
      "caption": "Supplier communication"
    },
    {
      "id": "seed-025",
      "type": "heading",
      "eyebrow": "07",
      "text": "72-Hour Creative Sprint",
      "level": 2
    },
    {
      "id": "seed-026",
      "type": "paragraph",
      "text": "A major part of the initial brand system was created during an intensive three-day independent sprint.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-027",
      "type": "timeline",
      "items": [
        {
          "id": "seed-028",
          "label": "Day 01",
          "title": "Strategy",
          "items": [
            "Naming",
            "Storytelling",
            "Fragrance concepts",
            "Brand positioning"
          ]
        },
        {
          "id": "seed-029",
          "label": "Day 02",
          "title": "Identity",
          "items": [
            "Logo",
            "Typography",
            "Labels",
            "Packaging direction",
            "Bottle concepts"
          ]
        },
        {
          "id": "seed-030",
          "label": "Day 03",
          "title": "Content",
          "items": [
            "Campaign imagery",
            "Social media",
            "Website concept",
            "Video",
            "Digital content"
          ]
        }
      ],
      "note": "Product development, supplier research, and fragrance prototyping continued beyond the initial three-day sprint."
    },
    {
      "id": "seed-031",
      "type": "heading",
      "eyebrow": "08",
      "text": "AI-Assisted Creative Direction",
      "level": 2
    },
    {
      "id": "seed-032",
      "type": "paragraph",
      "text": "Generative AI was used as a production tool rather than a substitute for creative direction. I independently curated references, developed prompts, evaluated outputs, directed revisions, and completed final image refinement and retouching.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-033",
      "type": "process",
      "steps": [
        {
          "id": "seed-034",
          "title": "Reference research",
          "description": ""
        },
        {
          "id": "seed-035",
          "title": "Reference curation",
          "description": ""
        },
        {
          "id": "seed-036",
          "title": "Prompt development",
          "description": ""
        },
        {
          "id": "seed-037",
          "title": "Generation",
          "description": ""
        },
        {
          "id": "seed-038",
          "title": "Evaluation",
          "description": ""
        },
        {
          "id": "seed-039",
          "title": "Prompt revision",
          "description": ""
        },
        {
          "id": "seed-040",
          "title": "Multiple iterations",
          "description": ""
        },
        {
          "id": "seed-041",
          "title": "Image selection",
          "description": ""
        },
        {
          "id": "seed-042",
          "title": "Retouching",
          "description": ""
        },
        {
          "id": "seed-043",
          "title": "Final visual direction",
          "description": ""
        }
      ]
    },
    {
      "id": "seed-044",
      "type": "image_sequence",
      "steps": [
        {
          "id": "seed-045",
          "label": "Reference",
          "media": null,
          "caption": ""
        },
        {
          "id": "seed-046",
          "label": "Initial output",
          "media": null,
          "caption": ""
        },
        {
          "id": "seed-047",
          "label": "Revision",
          "media": null,
          "caption": ""
        },
        {
          "id": "seed-048",
          "label": "Retouching",
          "media": null,
          "caption": ""
        },
        {
          "id": "seed-049",
          "label": "Final image",
          "media": null,
          "caption": ""
        }
      ],
      "caption": "From reference to final image"
    },
    {
      "id": "seed-050",
      "type": "heading",
      "eyebrow": "09",
      "text": "Digital Presence",
      "level": 2
    },
    {
      "id": "seed-051",
      "type": "paragraph",
      "text": "Instagram imagery, campaign content, website concepts, product upload concepts, video, motion content, and social media feed layouts.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-052",
      "type": "image_grid",
      "images": [],
      "columns": 3,
      "aspect": "square",
      "caption": "Social media feed layout"
    },
    {
      "id": "seed-053",
      "type": "video",
      "media": null,
      "url": "",
      "poster": null,
      "autoplay": true,
      "loop": true,
      "caption": "Motion content"
    },
    {
      "id": "seed-054",
      "type": "link",
      "label": "Instagram",
      "url": "",
      "style": "button",
      "description": "Follow the brand on Instagram"
    },
    {
      "id": "seed-055",
      "type": "heading",
      "eyebrow": "10",
      "text": "My Role",
      "level": 2
    },
    {
      "id": "seed-056",
      "type": "role_tools",
      "role": [
        "Brand Strategy",
        "Creative Direction",
        "Copywriting",
        "Naming",
        "Storytelling",
        "Fragrance Concept Development",
        "Visual Identity",
        "Logo Design",
        "Typography",
        "Label Design",
        "Packaging Concepts",
        "Supplier Research",
        "Art Direction",
        "Prompt Development",
        "AI-Assisted Visual Production",
        "Photo Retouching",
        "Social Media Content",
        "Web Design",
        "Video Content"
      ],
      "tools": [],
      "rows": [
        {
          "id": "seed-057",
          "label": "Status",
          "value": "In Development"
        },
        {
          "id": "seed-058",
          "label": "Timeline",
          "value": "2026–Present"
        }
      ]
    }
  ],
  "seoTitle": "",
  "seoDescription": ""
}$json$::jsonb, now())
on conflict (id) do nothing;

insert into public.project_drafts (project_id, content)
values ('11111111-1111-4111-8111-000000000001', $json${
  "title": "MAISON DE L’ÉTÉ",
  "slug": "maison-de-lete",
  "subtitle": "Independent Fragrance Brand Development",
  "categories": [
    "Brand Development",
    "Creative Direction",
    "Product Development",
    "Visual Identity"
  ],
  "year": "2026",
  "dateRange": "2026–Present",
  "projectStatus": "In Development",
  "shortDescription": "An independently developed fragrance brand, taken from first concept through brand strategy, fragrance direction, visual identity, product prototyping, and supplier research.",
  "cover": null,
  "coverVideo": null,
  "tags": [
    "Fragrance",
    "Branding",
    "Packaging",
    "AI-Assisted Production"
  ],
  "projectUrl": "",
  "projectUrlLabel": "",
  "socialUrl": "",
  "socialLabel": "Instagram",
  "role": [
    "Founder",
    "Brand Strategy",
    "Creative Direction",
    "Product Development"
  ],
  "tools": [],
  "blocks": [
    {
      "id": "seed-001",
      "type": "paragraph",
      "text": "I independently developed MAISON DE L’ÉTÉ from its initial concept through brand strategy, fragrance direction, visual identity, product prototyping, supplier research, and digital content development.",
      "style": "lead",
      "columns": 1
    },
    {
      "id": "seed-002",
      "type": "caption",
      "text": "An active pre-launch project: the brand is in product development and has not been commercially released."
    },
    {
      "id": "seed-003",
      "type": "image_full",
      "media": null,
      "caption": "Campaign direction",
      "tag": ""
    },
    {
      "id": "seed-004",
      "type": "heading",
      "eyebrow": "01",
      "text": "Concept",
      "level": 2
    },
    {
      "id": "seed-005",
      "type": "paragraph",
      "text": "The concept phase defined the brand’s positioning, storytelling, naming, slogans, and copywriting, and shaped an emotional brand world around a clearly defined target customer and visual direction.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-006",
      "type": "image_large",
      "media": null,
      "caption": "Brand positioning and storytelling",
      "tag": ""
    },
    {
      "id": "seed-007",
      "type": "heading",
      "eyebrow": "02",
      "text": "Research & References",
      "level": 2
    },
    {
      "id": "seed-008",
      "type": "paragraph",
      "text": "Research informed every part of the brand: fragrance direction, packaging, photography, typography, product styling, and visual identity.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-009",
      "type": "moodboard",
      "images": [],
      "columns": 4,
      "caption": "Reference and moodboard imagery"
    },
    {
      "id": "seed-010",
      "type": "heading",
      "eyebrow": "03",
      "text": "Fragrance Development",
      "level": 2
    },
    {
      "id": "seed-011",
      "type": "paragraph",
      "text": "The project includes original fragrance concepts and custom physical prototypes. Custom fragrance prototypes were commissioned through independent perfumers.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-012",
      "type": "fragrance",
      "name": "When Summer Sleeps",
      "status": "Prototype",
      "story": "",
      "topNotes": "",
      "middleNotes": "",
      "baseNotes": "",
      "referenceImages": [],
      "prototypeImage": null,
      "prototypeCaption": "",
      "notes": ""
    },
    {
      "id": "seed-013",
      "type": "heading",
      "eyebrow": "04",
      "text": "Visual Identity",
      "level": 2
    },
    {
      "id": "seed-014",
      "type": "paragraph",
      "text": "Logo development, typography, label design, business card design, and the wider visual system, including the iterations behind each decision. Designs that were not physically manufactured are labelled as design concepts.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-015",
      "type": "image_grid",
      "images": [],
      "columns": 3,
      "aspect": "natural",
      "caption": "Logo development, typography, labels and business cards"
    },
    {
      "id": "seed-016",
      "type": "heading",
      "eyebrow": "05",
      "text": "Product & Packaging",
      "level": 2
    },
    {
      "id": "seed-017",
      "type": "paragraph",
      "text": "Perfume bottle design concepts, label applications, packaging concepts, mockups, iterations, and AI-assisted renderings. Conceptual renderings are presented as design concepts, not manufactured products.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-018",
      "type": "image_two_column",
      "images": [
        {
          "id": "seed-019",
          "media": null,
          "caption": "",
          "tag": "Design Concept"
        },
        {
          "id": "seed-020",
          "media": null,
          "caption": "",
          "tag": "Design Concept"
        }
      ]
    },
    {
      "id": "seed-021",
      "type": "image_grid",
      "images": [],
      "columns": 3,
      "aspect": "natural",
      "caption": "Packaging concepts and iterations"
    },
    {
      "id": "seed-022",
      "type": "heading",
      "eyebrow": "06",
      "text": "Production Research",
      "level": 2
    },
    {
      "id": "seed-023",
      "type": "paragraph",
      "text": "Research included contacting fragrance suppliers, perfume bottle manufacturers, packaging suppliers, printing suppliers, fragrance workshops, and workshops in Grasse, France. The purpose was to evaluate price, minimum order quantity, sourcing, production feasibility, and manufacturing options.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-024",
      "type": "image_grid",
      "images": [],
      "columns": 2,
      "aspect": "natural",
      "caption": "Supplier communication"
    },
    {
      "id": "seed-025",
      "type": "heading",
      "eyebrow": "07",
      "text": "72-Hour Creative Sprint",
      "level": 2
    },
    {
      "id": "seed-026",
      "type": "paragraph",
      "text": "A major part of the initial brand system was created during an intensive three-day independent sprint.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-027",
      "type": "timeline",
      "items": [
        {
          "id": "seed-028",
          "label": "Day 01",
          "title": "Strategy",
          "items": [
            "Naming",
            "Storytelling",
            "Fragrance concepts",
            "Brand positioning"
          ]
        },
        {
          "id": "seed-029",
          "label": "Day 02",
          "title": "Identity",
          "items": [
            "Logo",
            "Typography",
            "Labels",
            "Packaging direction",
            "Bottle concepts"
          ]
        },
        {
          "id": "seed-030",
          "label": "Day 03",
          "title": "Content",
          "items": [
            "Campaign imagery",
            "Social media",
            "Website concept",
            "Video",
            "Digital content"
          ]
        }
      ],
      "note": "Product development, supplier research, and fragrance prototyping continued beyond the initial three-day sprint."
    },
    {
      "id": "seed-031",
      "type": "heading",
      "eyebrow": "08",
      "text": "AI-Assisted Creative Direction",
      "level": 2
    },
    {
      "id": "seed-032",
      "type": "paragraph",
      "text": "Generative AI was used as a production tool rather than a substitute for creative direction. I independently curated references, developed prompts, evaluated outputs, directed revisions, and completed final image refinement and retouching.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-033",
      "type": "process",
      "steps": [
        {
          "id": "seed-034",
          "title": "Reference research",
          "description": ""
        },
        {
          "id": "seed-035",
          "title": "Reference curation",
          "description": ""
        },
        {
          "id": "seed-036",
          "title": "Prompt development",
          "description": ""
        },
        {
          "id": "seed-037",
          "title": "Generation",
          "description": ""
        },
        {
          "id": "seed-038",
          "title": "Evaluation",
          "description": ""
        },
        {
          "id": "seed-039",
          "title": "Prompt revision",
          "description": ""
        },
        {
          "id": "seed-040",
          "title": "Multiple iterations",
          "description": ""
        },
        {
          "id": "seed-041",
          "title": "Image selection",
          "description": ""
        },
        {
          "id": "seed-042",
          "title": "Retouching",
          "description": ""
        },
        {
          "id": "seed-043",
          "title": "Final visual direction",
          "description": ""
        }
      ]
    },
    {
      "id": "seed-044",
      "type": "image_sequence",
      "steps": [
        {
          "id": "seed-045",
          "label": "Reference",
          "media": null,
          "caption": ""
        },
        {
          "id": "seed-046",
          "label": "Initial output",
          "media": null,
          "caption": ""
        },
        {
          "id": "seed-047",
          "label": "Revision",
          "media": null,
          "caption": ""
        },
        {
          "id": "seed-048",
          "label": "Retouching",
          "media": null,
          "caption": ""
        },
        {
          "id": "seed-049",
          "label": "Final image",
          "media": null,
          "caption": ""
        }
      ],
      "caption": "From reference to final image"
    },
    {
      "id": "seed-050",
      "type": "heading",
      "eyebrow": "09",
      "text": "Digital Presence",
      "level": 2
    },
    {
      "id": "seed-051",
      "type": "paragraph",
      "text": "Instagram imagery, campaign content, website concepts, product upload concepts, video, motion content, and social media feed layouts.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-052",
      "type": "image_grid",
      "images": [],
      "columns": 3,
      "aspect": "square",
      "caption": "Social media feed layout"
    },
    {
      "id": "seed-053",
      "type": "video",
      "media": null,
      "url": "",
      "poster": null,
      "autoplay": true,
      "loop": true,
      "caption": "Motion content"
    },
    {
      "id": "seed-054",
      "type": "link",
      "label": "Instagram",
      "url": "",
      "style": "button",
      "description": "Follow the brand on Instagram"
    },
    {
      "id": "seed-055",
      "type": "heading",
      "eyebrow": "10",
      "text": "My Role",
      "level": 2
    },
    {
      "id": "seed-056",
      "type": "role_tools",
      "role": [
        "Brand Strategy",
        "Creative Direction",
        "Copywriting",
        "Naming",
        "Storytelling",
        "Fragrance Concept Development",
        "Visual Identity",
        "Logo Design",
        "Typography",
        "Label Design",
        "Packaging Concepts",
        "Supplier Research",
        "Art Direction",
        "Prompt Development",
        "AI-Assisted Visual Production",
        "Photo Retouching",
        "Social Media Content",
        "Web Design",
        "Video Content"
      ],
      "tools": [],
      "rows": [
        {
          "id": "seed-057",
          "label": "Status",
          "value": "In Development"
        },
        {
          "id": "seed-058",
          "label": "Timeline",
          "value": "2026–Present"
        }
      ]
    }
  ],
  "seoTitle": "",
  "seoDescription": ""
}$json$::jsonb)
on conflict (project_id) do nothing;

-- The Reader.
insert into public.projects (id, slug, status, is_featured, sort_order, content, published_at)
values ('11111111-1111-4111-8111-000000000002', 'the-reader', 'published', true, 2, $json${
  "title": "The Reader.",
  "slug": "the-reader",
  "subtitle": "Product Concept · UX/UI · Branding · AI-Assisted Development",
  "categories": [
    "Product",
    "UX/UI",
    "Branding"
  ],
  "year": "",
  "dateRange": "",
  "projectStatus": "In Development",
  "shortDescription": "A minimalist bilingual e-reader designed to reduce friction between reading, dictionary lookup, and translation.",
  "cover": null,
  "coverVideo": null,
  "tags": [
    "Product Design",
    "Reading",
    "Language Learning"
  ],
  "projectUrl": "",
  "projectUrlLabel": "",
  "socialUrl": "",
  "socialLabel": "",
  "role": [
    "Product Concept",
    "UX/UI Direction",
    "Brand Identity",
    "Feature Planning",
    "Product Requirements",
    "Competitive Research",
    "AI-Assisted Development"
  ],
  "tools": [],
  "blocks": [
    {
      "id": "seed-059",
      "type": "paragraph",
      "text": "A minimalist bilingual e-reader designed to reduce friction between reading, dictionary lookup, and translation.",
      "style": "lead",
      "columns": 1
    },
    {
      "id": "seed-060",
      "type": "image_full",
      "media": null,
      "caption": "Current interface",
      "tag": ""
    },
    {
      "id": "seed-061",
      "type": "heading",
      "eyebrow": "01",
      "text": "The Problem",
      "level": 2
    },
    {
      "id": "seed-062",
      "type": "paragraph",
      "text": "Existing reading tools often interrupt the reading experience by separating vocabulary lookup, translation, and text navigation.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-063",
      "type": "heading",
      "eyebrow": "02",
      "text": "Product Features",
      "level": 2
    },
    {
      "id": "seed-064",
      "type": "paragraph",
      "text": "TXT support\nEPUB support\nDictionary\nTranslation\nHighlighting\nBookmarks\nSaved vocabulary\nCustom fonts\nMultilingual expansion",
      "style": "body",
      "columns": 2
    },
    {
      "id": "seed-065",
      "type": "image_grid",
      "images": [],
      "columns": 3,
      "aspect": "natural",
      "caption": "Feature details"
    },
    {
      "id": "seed-066",
      "type": "heading",
      "eyebrow": "03",
      "text": "Process",
      "level": 2
    },
    {
      "id": "seed-067",
      "type": "paragraph",
      "text": "From the initial concept through interface iterations to the current interface.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-068",
      "type": "image_sequence",
      "steps": [
        {
          "id": "seed-069",
          "label": "Initial concept",
          "media": null,
          "caption": ""
        },
        {
          "id": "seed-070",
          "label": "Interface iterations",
          "media": null,
          "caption": ""
        },
        {
          "id": "seed-071",
          "label": "Current interface",
          "media": null,
          "caption": ""
        }
      ],
      "caption": ""
    },
    {
      "id": "seed-072",
      "type": "heading",
      "eyebrow": "04",
      "text": "My Role",
      "level": 2
    },
    {
      "id": "seed-073",
      "type": "role_tools",
      "role": [
        "Product Concept",
        "UX/UI Direction",
        "Brand Identity",
        "Feature Planning",
        "Product Requirements",
        "Competitive Research",
        "AI-Assisted Development"
      ],
      "tools": [],
      "rows": [
        {
          "id": "seed-074",
          "label": "Status",
          "value": "In Development"
        },
        {
          "id": "seed-075",
          "label": "Source code",
          "value": "Maintained in a private repository"
        }
      ]
    },
    {
      "id": "seed-076",
      "type": "caption",
      "text": "Source code is maintained in a private repository."
    }
  ],
  "seoTitle": "",
  "seoDescription": ""
}$json$::jsonb, now())
on conflict (id) do nothing;

insert into public.project_drafts (project_id, content)
values ('11111111-1111-4111-8111-000000000002', $json${
  "title": "The Reader.",
  "slug": "the-reader",
  "subtitle": "Product Concept · UX/UI · Branding · AI-Assisted Development",
  "categories": [
    "Product",
    "UX/UI",
    "Branding"
  ],
  "year": "",
  "dateRange": "",
  "projectStatus": "In Development",
  "shortDescription": "A minimalist bilingual e-reader designed to reduce friction between reading, dictionary lookup, and translation.",
  "cover": null,
  "coverVideo": null,
  "tags": [
    "Product Design",
    "Reading",
    "Language Learning"
  ],
  "projectUrl": "",
  "projectUrlLabel": "",
  "socialUrl": "",
  "socialLabel": "",
  "role": [
    "Product Concept",
    "UX/UI Direction",
    "Brand Identity",
    "Feature Planning",
    "Product Requirements",
    "Competitive Research",
    "AI-Assisted Development"
  ],
  "tools": [],
  "blocks": [
    {
      "id": "seed-059",
      "type": "paragraph",
      "text": "A minimalist bilingual e-reader designed to reduce friction between reading, dictionary lookup, and translation.",
      "style": "lead",
      "columns": 1
    },
    {
      "id": "seed-060",
      "type": "image_full",
      "media": null,
      "caption": "Current interface",
      "tag": ""
    },
    {
      "id": "seed-061",
      "type": "heading",
      "eyebrow": "01",
      "text": "The Problem",
      "level": 2
    },
    {
      "id": "seed-062",
      "type": "paragraph",
      "text": "Existing reading tools often interrupt the reading experience by separating vocabulary lookup, translation, and text navigation.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-063",
      "type": "heading",
      "eyebrow": "02",
      "text": "Product Features",
      "level": 2
    },
    {
      "id": "seed-064",
      "type": "paragraph",
      "text": "TXT support\nEPUB support\nDictionary\nTranslation\nHighlighting\nBookmarks\nSaved vocabulary\nCustom fonts\nMultilingual expansion",
      "style": "body",
      "columns": 2
    },
    {
      "id": "seed-065",
      "type": "image_grid",
      "images": [],
      "columns": 3,
      "aspect": "natural",
      "caption": "Feature details"
    },
    {
      "id": "seed-066",
      "type": "heading",
      "eyebrow": "03",
      "text": "Process",
      "level": 2
    },
    {
      "id": "seed-067",
      "type": "paragraph",
      "text": "From the initial concept through interface iterations to the current interface.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-068",
      "type": "image_sequence",
      "steps": [
        {
          "id": "seed-069",
          "label": "Initial concept",
          "media": null,
          "caption": ""
        },
        {
          "id": "seed-070",
          "label": "Interface iterations",
          "media": null,
          "caption": ""
        },
        {
          "id": "seed-071",
          "label": "Current interface",
          "media": null,
          "caption": ""
        }
      ],
      "caption": ""
    },
    {
      "id": "seed-072",
      "type": "heading",
      "eyebrow": "04",
      "text": "My Role",
      "level": 2
    },
    {
      "id": "seed-073",
      "type": "role_tools",
      "role": [
        "Product Concept",
        "UX/UI Direction",
        "Brand Identity",
        "Feature Planning",
        "Product Requirements",
        "Competitive Research",
        "AI-Assisted Development"
      ],
      "tools": [],
      "rows": [
        {
          "id": "seed-074",
          "label": "Status",
          "value": "In Development"
        },
        {
          "id": "seed-075",
          "label": "Source code",
          "value": "Maintained in a private repository"
        }
      ]
    },
    {
      "id": "seed-076",
      "type": "caption",
      "text": "Source code is maintained in a private repository."
    }
  ],
  "seoTitle": "",
  "seoDescription": ""
}$json$::jsonb)
on conflict (project_id) do nothing;

-- Poshmark & eBay Reselling
insert into public.projects (id, slug, status, is_featured, sort_order, content, published_at)
values ('11111111-1111-4111-8111-000000000003', 'poshmark-ebay-reselling', 'published', false, 3, $json${
  "title": "Poshmark & eBay Reselling",
  "slug": "poshmark-ebay-reselling",
  "subtitle": "E-Commerce · Pricing · Merchandising · Customer Experience",
  "categories": [
    "E-Commerce",
    "Pricing",
    "Merchandising",
    "Customer Experience"
  ],
  "year": "",
  "dateRange": "",
  "projectStatus": "Ongoing",
  "shortDescription": "Independently managing product selection, pricing, photography, listing optimization, customer communication, fulfillment, and post-sale service across online resale marketplaces.",
  "cover": null,
  "coverVideo": null,
  "tags": [
    "E-Commerce",
    "Marketplaces",
    "Merchandising"
  ],
  "projectUrl": "",
  "projectUrlLabel": "",
  "socialUrl": "",
  "socialLabel": "",
  "role": [
    "Product Selection",
    "Pricing",
    "Photography",
    "Listing Optimization",
    "Customer Communication",
    "Fulfillment"
  ],
  "tools": [],
  "blocks": [
    {
      "id": "seed-077",
      "type": "paragraph",
      "text": "Independently manage product selection, pricing, photography, listing optimization, customer communication, fulfillment, and post-sale service across online resale marketplaces.",
      "style": "lead",
      "columns": 1
    },
    {
      "id": "seed-078",
      "type": "stats",
      "items": [
        {
          "id": "seed-079",
          "value": "",
          "label": "Items sold"
        },
        {
          "id": "seed-080",
          "value": "",
          "label": "Revenue"
        },
        {
          "id": "seed-081",
          "value": "",
          "label": "Active listings"
        },
        {
          "id": "seed-082",
          "value": "",
          "label": "Seller rating"
        }
      ],
      "note": ""
    },
    {
      "id": "seed-083",
      "type": "role_tools",
      "role": [],
      "tools": [],
      "rows": [
        {
          "id": "seed-084",
          "label": "Platforms",
          "value": "Poshmark, eBay"
        },
        {
          "id": "seed-085",
          "label": "Product category",
          "value": ""
        }
      ]
    },
    {
      "id": "seed-086",
      "type": "heading",
      "eyebrow": "01",
      "text": "Merchandising & Listings",
      "level": 2
    },
    {
      "id": "seed-087",
      "type": "paragraph",
      "text": "Product photography, listing presentation, and merchandising across both marketplaces.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-088",
      "type": "image_grid",
      "images": [],
      "columns": 3,
      "aspect": "square",
      "caption": "Product photos and listings"
    },
    {
      "id": "seed-089",
      "type": "heading",
      "eyebrow": "02",
      "text": "Pricing",
      "level": 2
    },
    {
      "id": "seed-090",
      "type": "paragraph",
      "text": "Pricing examples and how listings were positioned against comparable items.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-091",
      "type": "image_grid",
      "images": [],
      "columns": 2,
      "aspect": "natural",
      "caption": "Pricing examples"
    },
    {
      "id": "seed-092",
      "type": "heading",
      "eyebrow": "03",
      "text": "Customer Experience",
      "level": 2
    },
    {
      "id": "seed-093",
      "type": "paragraph",
      "text": "Customer communication, fulfillment, and post-sale service.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-094",
      "type": "image_grid",
      "images": [],
      "columns": 2,
      "aspect": "natural",
      "caption": "Sales and customer experience"
    }
  ],
  "seoTitle": "",
  "seoDescription": ""
}$json$::jsonb, now())
on conflict (id) do nothing;

insert into public.project_drafts (project_id, content)
values ('11111111-1111-4111-8111-000000000003', $json${
  "title": "Poshmark & eBay Reselling",
  "slug": "poshmark-ebay-reselling",
  "subtitle": "E-Commerce · Pricing · Merchandising · Customer Experience",
  "categories": [
    "E-Commerce",
    "Pricing",
    "Merchandising",
    "Customer Experience"
  ],
  "year": "",
  "dateRange": "",
  "projectStatus": "Ongoing",
  "shortDescription": "Independently managing product selection, pricing, photography, listing optimization, customer communication, fulfillment, and post-sale service across online resale marketplaces.",
  "cover": null,
  "coverVideo": null,
  "tags": [
    "E-Commerce",
    "Marketplaces",
    "Merchandising"
  ],
  "projectUrl": "",
  "projectUrlLabel": "",
  "socialUrl": "",
  "socialLabel": "",
  "role": [
    "Product Selection",
    "Pricing",
    "Photography",
    "Listing Optimization",
    "Customer Communication",
    "Fulfillment"
  ],
  "tools": [],
  "blocks": [
    {
      "id": "seed-077",
      "type": "paragraph",
      "text": "Independently manage product selection, pricing, photography, listing optimization, customer communication, fulfillment, and post-sale service across online resale marketplaces.",
      "style": "lead",
      "columns": 1
    },
    {
      "id": "seed-078",
      "type": "stats",
      "items": [
        {
          "id": "seed-079",
          "value": "",
          "label": "Items sold"
        },
        {
          "id": "seed-080",
          "value": "",
          "label": "Revenue"
        },
        {
          "id": "seed-081",
          "value": "",
          "label": "Active listings"
        },
        {
          "id": "seed-082",
          "value": "",
          "label": "Seller rating"
        }
      ],
      "note": ""
    },
    {
      "id": "seed-083",
      "type": "role_tools",
      "role": [],
      "tools": [],
      "rows": [
        {
          "id": "seed-084",
          "label": "Platforms",
          "value": "Poshmark, eBay"
        },
        {
          "id": "seed-085",
          "label": "Product category",
          "value": ""
        }
      ]
    },
    {
      "id": "seed-086",
      "type": "heading",
      "eyebrow": "01",
      "text": "Merchandising & Listings",
      "level": 2
    },
    {
      "id": "seed-087",
      "type": "paragraph",
      "text": "Product photography, listing presentation, and merchandising across both marketplaces.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-088",
      "type": "image_grid",
      "images": [],
      "columns": 3,
      "aspect": "square",
      "caption": "Product photos and listings"
    },
    {
      "id": "seed-089",
      "type": "heading",
      "eyebrow": "02",
      "text": "Pricing",
      "level": 2
    },
    {
      "id": "seed-090",
      "type": "paragraph",
      "text": "Pricing examples and how listings were positioned against comparable items.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-091",
      "type": "image_grid",
      "images": [],
      "columns": 2,
      "aspect": "natural",
      "caption": "Pricing examples"
    },
    {
      "id": "seed-092",
      "type": "heading",
      "eyebrow": "03",
      "text": "Customer Experience",
      "level": 2
    },
    {
      "id": "seed-093",
      "type": "paragraph",
      "text": "Customer communication, fulfillment, and post-sale service.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-094",
      "type": "image_grid",
      "images": [],
      "columns": 2,
      "aspect": "natural",
      "caption": "Sales and customer experience"
    }
  ],
  "seoTitle": "",
  "seoDescription": ""
}$json$::jsonb)
on conflict (project_id) do nothing;

-- Writing & Digital Publishing
insert into public.projects (id, slug, status, is_featured, sort_order, content, published_at)
values ('11111111-1111-4111-8111-000000000004', 'writing-digital-publishing', 'published', false, 4, $json${
  "title": "Writing & Digital Publishing",
  "slug": "writing-digital-publishing",
  "subtitle": "Independent Writing & Digital Publishing Project",
  "categories": [
    "Long-form Writing",
    "Cover Design",
    "EPUB Production",
    "Digital Publishing"
  ],
  "year": "",
  "dateRange": "",
  "projectStatus": "Independent Project",
  "shortDescription": "An independent long-form writing project produced end to end: manuscript, cover design, EPUB production, and digital publishing.",
  "cover": null,
  "coverVideo": null,
  "tags": [
    "Writing",
    "Publishing",
    "EPUB",
    "Canva"
  ],
  "projectUrl": "",
  "projectUrlLabel": "",
  "socialUrl": "",
  "socialLabel": "",
  "role": [
    "Long-form Writing",
    "Cover Design",
    "EPUB Production",
    "Digital Publishing"
  ],
  "tools": [
    "Canva"
  ],
  "blocks": [
    {
      "id": "seed-095",
      "type": "paragraph",
      "text": "An independent long-form writing project produced end to end: manuscript, cover design, EPUB production, and digital publishing.",
      "style": "lead",
      "columns": 1
    },
    {
      "id": "seed-096",
      "type": "image_large",
      "media": null,
      "caption": "Manuscript cover",
      "tag": ""
    },
    {
      "id": "seed-097",
      "type": "heading",
      "eyebrow": "01",
      "text": "Cover Design",
      "level": 2
    },
    {
      "id": "seed-098",
      "type": "paragraph",
      "text": "Cover design and book mockups produced for the manuscript.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-099",
      "type": "image_two_column",
      "images": [
        {
          "id": "seed-100",
          "media": null,
          "caption": "",
          "tag": ""
        },
        {
          "id": "seed-101",
          "media": null,
          "caption": "",
          "tag": ""
        }
      ]
    },
    {
      "id": "seed-102",
      "type": "heading",
      "eyebrow": "02",
      "text": "EPUB Production",
      "level": 2
    },
    {
      "id": "seed-103",
      "type": "paragraph",
      "text": "Screenshots and EPUB previews from the digital edition.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-104",
      "type": "image_grid",
      "images": [],
      "columns": 3,
      "aspect": "natural",
      "caption": "EPUB previews"
    },
    {
      "id": "seed-105",
      "type": "heading",
      "eyebrow": "03",
      "text": "Excerpt",
      "level": 2
    },
    {
      "id": "seed-106",
      "type": "quote",
      "text": "",
      "attribution": ""
    },
    {
      "id": "seed-107",
      "type": "heading",
      "eyebrow": "04",
      "text": "My Role",
      "level": 2
    },
    {
      "id": "seed-108",
      "type": "role_tools",
      "role": [
        "Long-form Writing",
        "Cover Design",
        "EPUB Production",
        "Digital Publishing"
      ],
      "tools": [
        "Canva"
      ],
      "rows": []
    }
  ],
  "seoTitle": "",
  "seoDescription": ""
}$json$::jsonb, now())
on conflict (id) do nothing;

insert into public.project_drafts (project_id, content)
values ('11111111-1111-4111-8111-000000000004', $json${
  "title": "Writing & Digital Publishing",
  "slug": "writing-digital-publishing",
  "subtitle": "Independent Writing & Digital Publishing Project",
  "categories": [
    "Long-form Writing",
    "Cover Design",
    "EPUB Production",
    "Digital Publishing"
  ],
  "year": "",
  "dateRange": "",
  "projectStatus": "Independent Project",
  "shortDescription": "An independent long-form writing project produced end to end: manuscript, cover design, EPUB production, and digital publishing.",
  "cover": null,
  "coverVideo": null,
  "tags": [
    "Writing",
    "Publishing",
    "EPUB",
    "Canva"
  ],
  "projectUrl": "",
  "projectUrlLabel": "",
  "socialUrl": "",
  "socialLabel": "",
  "role": [
    "Long-form Writing",
    "Cover Design",
    "EPUB Production",
    "Digital Publishing"
  ],
  "tools": [
    "Canva"
  ],
  "blocks": [
    {
      "id": "seed-095",
      "type": "paragraph",
      "text": "An independent long-form writing project produced end to end: manuscript, cover design, EPUB production, and digital publishing.",
      "style": "lead",
      "columns": 1
    },
    {
      "id": "seed-096",
      "type": "image_large",
      "media": null,
      "caption": "Manuscript cover",
      "tag": ""
    },
    {
      "id": "seed-097",
      "type": "heading",
      "eyebrow": "01",
      "text": "Cover Design",
      "level": 2
    },
    {
      "id": "seed-098",
      "type": "paragraph",
      "text": "Cover design and book mockups produced for the manuscript.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-099",
      "type": "image_two_column",
      "images": [
        {
          "id": "seed-100",
          "media": null,
          "caption": "",
          "tag": ""
        },
        {
          "id": "seed-101",
          "media": null,
          "caption": "",
          "tag": ""
        }
      ]
    },
    {
      "id": "seed-102",
      "type": "heading",
      "eyebrow": "02",
      "text": "EPUB Production",
      "level": 2
    },
    {
      "id": "seed-103",
      "type": "paragraph",
      "text": "Screenshots and EPUB previews from the digital edition.",
      "style": "body",
      "columns": 1
    },
    {
      "id": "seed-104",
      "type": "image_grid",
      "images": [],
      "columns": 3,
      "aspect": "natural",
      "caption": "EPUB previews"
    },
    {
      "id": "seed-105",
      "type": "heading",
      "eyebrow": "03",
      "text": "Excerpt",
      "level": 2
    },
    {
      "id": "seed-106",
      "type": "quote",
      "text": "",
      "attribution": ""
    },
    {
      "id": "seed-107",
      "type": "heading",
      "eyebrow": "04",
      "text": "My Role",
      "level": 2
    },
    {
      "id": "seed-108",
      "type": "role_tools",
      "role": [
        "Long-form Writing",
        "Cover Design",
        "EPUB Production",
        "Digital Publishing"
      ],
      "tools": [
        "Canva"
      ],
      "rows": []
    }
  ],
  "seoTitle": "",
  "seoDescription": ""
}$json$::jsonb)
on conflict (project_id) do nothing;

